#!/usr/bin/env python3
"""Inventory supplied repository archives without extracting or executing them."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from collections import Counter, defaultdict
from pathlib import Path
from zipfile import BadZipFile, ZipFile


CODE_SUFFIXES = {
    ".c", ".cc", ".cpp", ".css", ".go", ".html", ".java", ".js", ".jsx",
    ".json", ".py", ".rb", ".rs", ".sh", ".sql", ".tsx", ".ts", ".vue",
    ".xml", ".yaml", ".yml",
}
DOC_SUFFIXES = {".md", ".pdf", ".rst", ".txt"}
SECRET_NAME_RE = re.compile(
    r"(^|/)(\.env(?:\..*)?|\.secrets(?:\..*)?|.*(?:cookies?|storage_state|credentials?)\.(?:json|yaml|yml|txt)?|.*\.(?:pem|key))$",
    re.IGNORECASE,
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def archive_record(path: Path) -> dict:
    record = {
        "name": path.name,
        "sha256": sha256(path),
        "bytes": path.stat().st_size,
        "valid_zip": True,
        "entries": 0,
        "uncompressed_bytes": 0,
        "code_files": 0,
        "doc_files": 0,
        "extensions": {},
        "top_levels": [],
        "suspicious_paths": [],
        "path_traversal": [],
    }
    try:
        with ZipFile(path) as archive:
            infos = [info for info in archive.infolist() if not info.is_dir()]
            names = [info.filename for info in infos]
            record["entries"] = len(infos)
            record["uncompressed_bytes"] = sum(info.file_size for info in infos)
            record["code_files"] = sum(Path(name).suffix.lower() in CODE_SUFFIXES for name in names)
            record["doc_files"] = sum(Path(name).suffix.lower() in DOC_SUFFIXES for name in names)
            record["extensions"] = dict(sorted(Counter(Path(name).suffix.lower() or "[none]" for name in names).items()))
            record["top_levels"] = sorted({name.split("/", 1)[0] for name in names if name})
            record["suspicious_paths"] = [name for name in names if SECRET_NAME_RE.search(name)]
            record["path_traversal"] = [
                name for name in names
                if any(part in {"", ".", ".."} and part == ".." for part in Path(name).parts)
                or name.startswith(("/", "\\"))
            ]
    except BadZipFile as exc:
        record["valid_zip"] = False
        record["error"] = str(exc)
    return record


def directory_record(path: Path) -> dict:
    files = sorted(p for p in path.rglob("*") if p.is_file())
    return {
        "name": path.name,
        "kind": "directory",
        "files": len(files),
        "bytes": sum(p.stat().st_size for p in files),
        "extensions": dict(sorted(Counter(p.suffix.lower() or "[none]" for p in files).items())),
        "files_sample": [p.relative_to(path).as_posix() for p in files[:40]],
    }


def build_report(root: Path) -> dict:
    archives = [archive_record(path) for path in sorted(root.glob("*.zip"))]
    groups: defaultdict[str, list[str]] = defaultdict(list)
    for record in archives:
        groups[record["sha256"]].append(record["name"])
    for record in archives:
        record["duplicate_group"] = groups[record["sha256"]] if len(groups[record["sha256"]]) > 1 else []
    directories = [directory_record(path) for path in sorted(root.iterdir()) if path.is_dir() and path.name != ".git"]
    return {
        "schema": 1,
        "source_root": root.name,
        "archive_count": len(archives),
        "directory_count": len(directories),
        "archives": archives,
        "directories": directories,
    }


def markdown(report: dict) -> str:
    lines = [
        "# Supplied Repository Archive Audit",
        "",
        "Generated by `scripts/audit_zip_repositories.py`. This report inventories archive metadata only; it does not execute archive contents.",
        "",
        f"- ZIP archives: **{report['archive_count']}**",
        f"- Source directories: **{report['directory_count']}**",
        "",
        "| Archive | Compressed | Entries | Code | Docs | Security/path flags | Exact duplicate |",
        "|---|---:|---:|---:|---:|---:|---|",
    ]
    for item in report["archives"]:
        flags = len(item["suspicious_paths"]) + len(item["path_traversal"])
        duplicate = ", ".join(item["duplicate_group"]) if item["duplicate_group"] else "—"
        lines.append(
            f"| `{item['name']}` | {item['bytes']:,} B | {item['entries']:,} | "
            f"{item['code_files']:,} | {item['doc_files']:,} | {flags} | {duplicate} |"
        )
    lines.extend(["", "## Source directories", "", "| Directory | Files | Bytes |", "|---|---:|---:|"])
    for item in report["directories"]:
        lines.append(f"| `{item['name']}` | {item['files']:,} | {item['bytes']:,} |")
    lines.extend(["", "## Interpretation", "", "See `research/ZIP_REPOSITORY_ECOSYSTEM_AUDIT.md` for the curated capability and licensing analysis.", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("root", type=Path, nargs="?", default=Path("zip-repos"))
    parser.add_argument("--json-out", type=Path, default=Path("provenance/ZIP_REPOSITORY_MANIFEST.json"))
    parser.add_argument("--markdown-out", type=Path, default=Path("research/generated/ZIP_REPOSITORY_INVENTORY.md"))
    args = parser.parse_args()
    report = build_report(args.root)
    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.markdown_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    args.markdown_out.write_text(markdown(report), encoding="utf-8")
    print(json.dumps({"archives": report["archive_count"], "directories": report["directory_count"], "json": str(args.json_out), "markdown": str(args.markdown_out)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
