#!/usr/bin/env python3
"""Audit extracted repository snapshots without executing or modifying them."""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path


SKIP_DIRS = {".git", "node_modules", ".venv", "venv", "__pycache__", ".cache", "dist", "build", ".next", ".tox"}
CODE_SUFFIXES = {".c", ".cc", ".cpp", ".css", ".go", ".html", ".java", ".js", ".jsx", ".py", ".rb", ".rs", ".sh", ".sql", ".ts", ".tsx", ".vue", ".xml", ".yaml", ".yml"}
DOC_SUFFIXES = {".md", ".pdf", ".rst", ".txt"}
SENSITIVE_NAME_RE = re.compile(r"(^|/)(\.env(?:\..*)?|\.secrets(?:\..*)?|.*(?:cookies?|storage_state|credentials?)\.(?:json|yaml|yml|txt)?|.*\.(?:pem|key))$", re.I)


def files_under(root: Path) -> list[Path]:
    return sorted(p for p in root.rglob("*") if p.is_file() and not any(part in SKIP_DIRS for part in p.relative_to(root).parts))


def readme_paths(root: Path) -> list[str]:
    paths = [p for p in root.iterdir() if p.is_file() and p.name.lower().startswith("readme")]
    return [p.relative_to(root).as_posix() for p in sorted(paths)]


def language_signals(path: Path) -> dict[str, int]:
    candidates = [path / "README.md"] + [p for p in path.iterdir() if p.is_file() and p.name.lower().startswith("readme")]
    text = ""
    for candidate in candidates:
        if candidate.is_file():
            text = candidate.read_text(encoding="utf-8", errors="ignore")[:200_000]
            if text:
                break
    ranges = {
        "cjk": (0x2E80, 0x9FFF),
        "arabic": (0x0600, 0x06FF),
        "korean": (0xAC00, 0xD7AF),
        "cyrillic": (0x0400, 0x04FF),
    }
    return {name: sum(lo <= ord(char) <= hi for char in text) for name, (lo, hi) in ranges.items()}


def record(path: Path) -> dict:
    files = files_under(path)
    relative = [p.relative_to(path).as_posix() for p in files]
    return {
        "name": path.name,
        "files": len(files),
        "bytes": sum(p.stat().st_size for p in files),
        "code_files": sum(p.suffix.lower() in CODE_SUFFIXES for p in files),
        "doc_files": sum(p.suffix.lower() in DOC_SUFFIXES for p in files),
        "extensions": dict(sorted(Counter(p.suffix.lower() or "[none]" for p in files).items())),
        "readmes": readme_paths(path),
        "licenses": [name for name in relative if Path(name).name.lower().startswith(("license", "copying"))],
        "sensitive_paths": [name for name in relative if SENSITIVE_NAME_RE.search(name)],
        "language_signals": language_signals(path),
    }


def build_report(root: Path) -> dict:
    dirs = [p for p in sorted(root.iterdir()) if p.is_dir() and p.name not in SKIP_DIRS]
    return {"schema": 1, "source_root": root.name, "directory_count": len(dirs), "directories": [record(p) for p in dirs]}


def markdown(report: dict) -> str:
    lines = ["# Extracted Repository Inventory", "", "Generated by `scripts/audit_extracted_repositories.py`; snapshots are read-only inputs and are never executed.", "", f"- Directories: **{report['directory_count']}**", "", "| Repository | Files | MiB | Code | Docs | README(s) | Sensitive paths |", "|---|---:|---:|---:|---:|---|---:|"]
    for item in report["directories"]:
        readmes = ", ".join(f"`{name}`" for name in item["readmes"]) or "—"
        lines.append(f"| `{item['name']}` | {item['files']:,} | {item['bytes'] / 1024 / 1024:.1f} | {item['code_files']:,} | {item['doc_files']:,} | {readmes} | {len(item['sensitive_paths'])} |")
    lines += ["", "## Handling", "", "Sensitive paths are reported by name only. Never copy cookies, browser state, credentials, private keys, personal identifiers, generated databases, or media blobs into the Hub. See `research/EXTRACTED_REPOSITORY_LANGUAGE_AUDIT.md` for translation and curation decisions.", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("root", type=Path)
    parser.add_argument("--json-out", type=Path, default=Path("provenance/EXTRACTED_REPOSITORY_MANIFEST.json"))
    parser.add_argument("--markdown-out", type=Path, default=Path("research/generated/EXTRACTED_REPOSITORY_INVENTORY.md"))
    args = parser.parse_args()
    report = build_report(args.root)
    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.markdown_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    args.markdown_out.write_text(markdown(report), encoding="utf-8")
    print(json.dumps({"directories": report["directory_count"], "json": str(args.json_out), "markdown": str(args.markdown_out)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
